stages:
  - build
  - compose-up
  - test
  - compose-down

build-job:
  tags:
    - slurm
  stage: build
  script:
    - docker build -t slurm:$(git rev-parse --short HEAD) .
    - echo "Compile complete."

compose-up-job:
  tags:
    - slurm
  stage: compose-up
  script:
    - SLURM_VERSION=$(git rev-parse --short HEAD) docker-compose -f docker-compose-github.yml up -d

compose-up-job:
  tags:
    - slurm
  stage: test
  script:
    - docker ps -a


compose-down-job:
  tags:
    - slurm
  stage: compose-down
  script:
    - SLURM_VERSION=$(git rev-parse --short HEAD) docker-compose -f docker-compose-github.yml down --remove-orphans -v