stages:
  - build
  - test

build-job:
  tags:
    - slurm
  stage: build
  script:
    - docker build -t slurm:$(git rev-parse --short HEAD) -f Dockerfiles/opensuse.Dockerfile .

test-slurm:
  tags:
    - slurm
  stage: test
  script:
    - SLURM_VERSION=$(git rev-parse --short HEAD) docker-compose -f docker-compose-gitlab.yml up -d
    - docker ps -a
    - docker exec login01 sinfo
    - docker exec -u hpcuser login01 /usr/local/bin/slurm_tests.sh
    - SLURM_VERSION=$(git rev-parse --short HEAD) docker-compose -f docker-compose-gitlab.yml down --remove-orphans -v
