stages:
  - build
  - test

build-job:
  tags:
    - slurm
  stage: build
  script:
    - docker build -t slurm:$(git rev-parse --short HEAD) .
    - echo "Compile complete."

test-slurm:
  tags:
    - slurm
  stage: test
  script:
    - SLURM_VERSION=$(git rev-parse --short HEAD) docker-compose -f docker-compose-github.yml up -d
    - docker ps -a
    - docker exec -it login01 sinfo
    - docker exec -it login01 /usr/local/bin/slurm_tests.sh
    - SLURM_VERSION=$(git rev-parse --short HEAD) docker-compose -f docker-compose-github.yml down --remove-orphans -v
