stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  tags:
    - slurm
  stage: build
  script:
    - docker build -t slurm:$(git rev-parse --short HEAD) .
    - echo "Compile complete."

