version: "2.2"

services:
  mysql:
    image: mariadb:10.10
    hostname: mysql
    container_name: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

  slurmdbd:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.6}
    build:
      context: .
      args:
        SLURM_TAG: ${SLURM_TAG:-slurm-23.11.6-6-1}
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
    expose:
      - "6819"
    depends_on:
      - mysql

  slurmctld:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.6}
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf:ro
    expose:
      - "6817"
    depends_on:
      - "slurmdbd"

  login01:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.6}
    command: ["slurmd"]
    hostname: login01
    container_name: login01
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./ssh:/home/hpcuser/.ssh
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf:ro
    expose:
      - "6818"
      - "22"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M


  node01:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.6}
    command: ["slurmd"]
    hostname: node01
    container_name: node01
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./ssh:/home/hpcuser/.ssh
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf:ro
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
  
  node02:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.6}
    command: ["slurmd"]
    hostname: node02
    container_name: node02
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./ssh:/home/hpcuser/.ssh
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf:ro
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M

  node03:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.6}
    command: ["slurmd"]
    hostname: node03
    container_name: node03
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./ssh:/home/hpcuser/.ssh
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf:ro
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
  node04:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.6}
    command: ["slurmd"]
    hostname: node04
    container_name: node04
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./ssh:/home/hpcuser/.ssh
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf:ro
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
  node05:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.6}
    command: ["slurmd"]
    hostname: node05
    container_name: node05
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./ssh:/home/hpcuser/.ssh
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf:ro
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M

  node06:
    image: slurm-docker-cluster:${IMAGE_TAG:-23.11.6}
    command: ["slurmd"]
    hostname: node06
    container_name: node06
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - ./ssh:/home/hpcuser/.ssh
      - ./slurm.conf:/etc/slurm/slurm.conf:ro
      - ./slurmdbd.conf:/etc/slurm/slurmdbd.conf:ro
    expose:
      - "6818"
    depends_on:
      - "slurmctld"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 50M
        reservations:
          cpus: '0.1'
          memory: 20M


volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
