name: slurm-cluster-tests
on: push
jobs:
  build-slurm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            SLURM_TAG=slurm-24-05-0-1
          file: Dockerfiles/rockylinux.Dockerfile
          context: .
          push: true
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/slurm-standalone:slurm-24-05-0-1
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Inspect
        run: |
          docker image inspect ghcr.io/${{ github.repository_owner }}/slurm-standalone:slurm-24-05-0-1

      - name: Test
        run: |
          docker run --rm -h node01 ghcr.io/${{ github.repository_owner }}/slurm-standalone:slurm-24-05-0-1 sinfo
          docker run --rm -h node01 ghcr.io/${{ github.repository_owner }}/slurm-standalone:slurm-24-05-0-1 squeue
          docker run --rm -h node01 ghcr.io/${{ github.repository_owner }}/slurm-standalone:slurm-24-05-0-1 /usr/local/bin/slurm_tests.sh
