name: slurm-cluster-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yml"
          test-container: login01
          test-command: "sinfo"
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yml"
          test-container: login01
          test-command: "squeue"
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yml"
          test-container: login01
          test-command: "srun -N 1 -n 1 hostname"
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yml"
          test-container: login01
          test-command: "srun -N 2 -n 2 hostname"
