name: slurm-cluster-tests
on: push
jobs:
  build-slurm:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            SLURM_TAG=slurm-21-08-6-1
          context: .
          push: true
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/slurm:slurm-21-08-6-1
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Inspect
        run: |
          docker image inspect ghcr.io/${{ github.repository_owner }}/slurm:slurm-21-08-6-1
      
  slurm-testing:
    needs: build-slurm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tylern4/docker-compose-action@v1.4.0
        with:
          compose-file: "./docker-compose.yml"
          test-container: login01
          test-command: "sinfo"
          
