name: slurm-cluster-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build the stack
        run: SLURM_TAG=slurm-23-11-6-1 IMAGE_TAG=23.11.6 docker-compose up -d
      - name: List Nodes
        run: docker-compose exec login01 sinfo
      - name: List Jobs
        run: docker-compose exec login01 squeue
      - name: List Hostnames
        run: docker-compose exec login01 srun -N 1 -n 1 hostname
