name: slurm-cluster-tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yml"
          test-container: login01
          test-command: |
            sinfo
            squeue
            srun -N 1 -n 1 hostname
            srun -N 2 -n 2 hostname
            sacct
