name: Run All Workflow

on:
  push:

jobs:
  version-matrix:
    strategy:
      fail-fast: false
      matrix:
        version: ["slurm-24-05-0-1", "slurm-21-08-6-1", "slurm-23-11-6-1"]
    uses: ./.github/workflows/run-one-workflow.yml
    with:
      version: ${{ fromJSON(matrix.version) }}
    secrets: inherit