name: Run One
on:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string
      os: # the variable you can use in place of a matrix
        required: true
        type: string
jobs:
  build-slurm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build
        uses: docker/build-push-action@v5
        with:
          build-args: |
            SLURM_TAG=${{ inputs.version }}
          context: .
          push: true
          load: true
          tags: ghcr.io/${{ github.repository_owner }}/slurm:${{ inputs.version }}-${{ inputs.os }}
          file: ./${{ inputs.os }}.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Inspect
        run: |
          docker image inspect ghcr.io/${{ github.repository_owner }}/slurm:${{ inputs.version }}-${{ inputs.os }}
      - name: Generate compose file
        run: |
          python3 -m pip install pyyaml
          python3 create_slurm.py ghcr.io/${{ github.repository_owner }}/slurm:${{ inputs.version }}-${{ inputs.os }}
      - name: Save compose yml
        uses: actions/cache/save@v4
        with:
          path: docker-compose-workflow.yml
          key: compose-workflow-${{ inputs.version }}-${{ inputs.os }}

  slurm-testing:
    needs: build-slurm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        with:
          path: docker-compose-workflow.yml
          key: compose-workflow-${{ inputs.version }}-${{ inputs.os }}
      - uses: tylern4/docker-compose-action@v1.4.0
        with:
          compose-file: "./docker-compose-workflow.yml"
          test-container: login01
          test-command: "sinfo"

      - uses: tylern4/docker-compose-action@v1.4.0
        with:
          compose-file: "./docker-compose-workflow.yml"
          test-container: login01
          test-command: "srun -N 1 -n 1 hostname"

      - uses: tylern4/docker-compose-action@v1.4.0
        with:
          compose-file: "./docker-compose-workflow.yml"
          test-container: login01
          test-command: "sacct"
